version: "3.9"

services:
  shopping:
    build:
      context: .
      dockerfile: Dockerfile.shopping
    restart: always
    ports:
      - "9063:9063"      
    env_file:
      - .env
    depends_on:
      - payment          
    environment:
      - PAYMENT_BASE_URL=http://payment:9053
    networks:
      - appnet

  payment:
    build:
      context: .
      dockerfile: Dockerfile.payment
    restart: always
    ports:
      - "9053:9053"     
    env_file:
      - .env
    networks:
      - appnet

networks:
  appnet:
